name: Pip
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.9", "3.11"]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools
    - name: Install Apache Arrow
      run: |
        if [ "${{ matrix.platform }}" == "ubuntu-latest" ]; then
          sudo apt update
          sudo apt install -y libapache-arrow-dev
        elif [ "${{ matrix.platform }}" == "macos-latest" ]; then
          brew install apache-arrow
        elif [ "${{ matrix.platform }}" == "windows-latest" ]; then
          choco install apache-arrow
        fi
    - name: Build and install
      run: pip install --verbose .
